### ISSUE TITLE
Fix prefix indent example

### ISSUE THREAD

**Issue by zlatanvasovic** [mdo/code-guide#19]
From https://github.com/mdo/code-guide#prefixed-properties:

``` css
.selector {
  -webkit-border-radius: 3px;
     -moz-border-radius: 3px;
          border-radius: 3px;
}
```

Prefixing border-radius isn't needed. Please change this example to something like:

``` css
.selector {
  -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.075);
          box-shadow: 0 1px 2px rgba(0,0,0,.075);
}
```
