### ISSUE TITLE
should  it have quotes or not in background image?

### ISSUE THREAD

**Issue by visamz** [mdo/code-guide#84]
two differents used in guide:

``` css
/* Multiple declarations, one per line */
.sprite {
  display: inline-block;
  width: 16px;
  height: 15px;
  background-image: url(../img/sprite.png);
}
```

the other:

``` css
/* Good example */
.element {
  margin-bottom: 10px;
  background-color: red;
  background-image: url("image.jpg");
  border-top-left-radius: 3px;
  border-top-right-radius: 3px;
}
```

should  it have quotes or not in background image?
`url(......)` or `url('......')` or `url("......")`?
